# Generated by Django 4.0.5 on 2022-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_dis',
            field=models.TextField(),
        ),
    ]
