from django.urls import path
from .import views
urlpatterns = [
    path('',views.index,name='index'),
    path('header/',views.header,name='header'),
    path('contact/',views.contact,name='contact'),
    path('products/',views.products,name='products'),
    path('category/',views.category,name='category'),
    path('clients/',views.clients,name='clients'),
    path('log/',views.log,name='log'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('change_pass/',views.change_pass,name='change_pass'),
    path('seller_header/',views.seller_header,name='seller_header'),
    path('seller_index/',views.seller_index,name='seller_index'),
    path('add_product/',views.add_product,name='add_product'),
    path('seller_product_details/<int:pk>/',views.seller_product_details,name='seller_product_details'),
    path('seller_edit_product/<int:pk>/',views.seller_edit_product,name='seller_edit_product'),
    path('seller_delete_product/<int:pk>/',views.seller_delete_product,name='seller_delete_product'),
    path('single_product/<int:pk>/',views.single_product,name='single_product'),
    path('add_to_wishlist/<int:pk>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove_to_wishlist/<int:pk>/',views.remove_to_wishlist,name='remove_to_wishlist'),
    path('add_to_cart/<int:pk>/',views.add_to_cart,name='add_to_cart'),
    path('cart/',views.cart,name='cart'),
    path('remove_to_cart/<int:pk>/',views.remove_to_cart,name='remove_to_cart'),
    path('change_qty/<int:pk>/',views.change_qty,name='change_qty'),
    path('pay/',views.initiate_payment, name='pay'),
    path('callback/',views.callback, name='callback'),
]